/*
 * generated by Xtext
 */
package be.unamur.coreal;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CoreALStandaloneSetup extends CoreALStandaloneSetupGenerated{

	public static void doSetup() {
		new CoreALStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

