/*
 * generated by Xtext
 */
package be.unamur.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CoreAlUiModule extends be.unamur.xtext.ui.AbstractCoreAlUiModule {
	public CoreAlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
