/*
 * generated by Xtext
 */
package be.unamur.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CoreAlUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return be.unamur.xtext.ui.internal.CoreAlActivator.getInstance().getInjector("be.unamur.xtext.CoreAl");
	}
	
}
