/*
 * generated by Xtext
 */
package be.unamur.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import be.unamur.xtext.services.CoreAlGrammarAccess;

public class CoreAlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CoreAlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected be.unamur.xtext.parser.antlr.internal.InternalCoreAlParser createParser(XtextTokenStream stream) {
		return new be.unamur.xtext.parser.antlr.internal.InternalCoreAlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Metamodel";
	}
	
	public CoreAlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CoreAlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
