/*
 * generated by Xtext
 */
package be.unamur.coreal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CoreALUiModule extends be.unamur.coreal.ui.AbstractCoreALUiModule {
	public CoreALUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
