/*
 * generated by Xtext
 */
package be.unamur.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CoreAlStandaloneSetup extends CoreAlStandaloneSetupGenerated{

	public static void doSetup() {
		new CoreAlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

