/*
 * generated by Xtext
 */
package be.unamur.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import be.unamur.xtext.ui.internal.CoreAlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CoreAlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CoreAlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CoreAlActivator.getInstance().getInjector(CoreAlActivator.BE_UNAMUR_XTEXT_COREAL);
	}
	
}
