/**
 * generated by Xtext
 */
package be.unamur.xtext.validation;

import be.unamur.xtext.validation.AbstractCoreAlValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CoreAlValidator extends AbstractCoreAlValidator {
}
