/*
 * generated by Xtext
 */
package be.unamur.coreal.ui.contentassist

import be.unamur.coreal.ui.contentassist.AbstractCoreALProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class CoreALProposalProvider extends AbstractCoreALProposalProvider {
}
