/*
 * generated by Xtext
 */
package be.unamur.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CoreAlRuntimeModule extends be.unamur.xtext.AbstractCoreAlRuntimeModule {

}
