/*
 * generated by Xtext
 */
package be.unamur.xtext.ui.contentassist

import be.unamur.xtext.ui.contentassist.AbstractCoreAlProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class CoreAlProposalProvider extends AbstractCoreAlProposalProvider {
}
